
package Vista;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.mariadb.jdbc.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import Modelo.Alumno;
import Modelo.Materia;
import Persistencia.AlumnoDatos;
import Persistencia.InscripcionData;
import Persistencia.MateriaData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Modelo.Conexion;


public class VistaInscripcion extends javax.swing.JFrame {

    //base de datos
    String url = "jdbc:mariadb://localhost:3306/tu_base";
    String usuario = "root";
    String password = "1234"; // cambia según tu contraseña

// Crear la conexión
    Connection con = null;
    
    private ArrayList<Materia> ListaM;
    private ArrayList<Alumno>  ListaA;
    
    private InscripcionData inscData;
    private MateriaData mData;
    private AlumnoDatos aData;
            
    private DefaultTableModel modelo;
    ResultSet rs ;

    public VistaInscripcion() {
        initComponents();
        
  
    Conexion c = new Conexion(url, usuario, password);
    Connection con = (Connection) c.buscarConexion(); 

        aData = new AlumnoDatos(con);
        inscData = new InscripcionData(con);

        ListaA = (ArrayList<Alumno>)aData.listarAlumnos();
        
        modelo = new DefaultTableModel();
        
        cargaAlumnos();
        armarCabeceraTabla();
    }
    //formularioInscripcion(){
  public void VistaInscripcion(){
      initComponents();
      
      aData = new AlumnoDatos();
      ListaA = (ArrayList<Alumno>) aData.listarAlumnos();
      modelo = new DefaultTableModel();
      inscData = new InscripcionData();
      mData = new MateriaData();
      
      cargaAlumnos();
      armarCabeceraTabla();
      
  }
//    
//    }
        private void cargaAlumnos() {
            for (Alumno items : ListaA) {
           jcalu.addItem(items);
            }
        
        }

    private void armarCabeceraTabla() {
       ArrayList<Object> filaCabecera = new ArrayList<>();
       filaCabecera.add("ID");
       filaCabecera.add("Nombre");
       filaCabecera.add("Año");
       
        for (Object it : filaCabecera) {
            modelo.addColumn(it);
        }
       jTable1.setModel(modelo);
    }
    
    private void borrarFilaTabla(){
    int indice = modelo.getRowCount()-1;
    
        for (int i = indice; i >= 0; i--) {
            modelo.removeRow(i);
        }
        
    }
    
    private void cargarDatosNoInscriptas(){
    
    Alumno select = (Alumno) jcalu.getSelectedItem();
//    ListaM = (ArrayList) inscData.obtenerMateriasNOCursadas(select.getIdAlumno());
    
        for (Materia m : ListaM) {
            modelo.addRow(new Object[] {m.getIdmateria(),m.getNombre(),m.getAnio() });
        }
    
    }

    private void cargarDatosInscriptas() {
    borrarFilaTabla();

    Alumno alumnoSeleccionado = (Alumno) jcalu.getSelectedItem();

    if (alumnoSeleccionado != null) {
        ArrayList<Materia> lista = (ArrayList<Materia>) inscData.obtenerMateriasCursadas(alumnoSeleccionado.getIdAlumno());

        for (Materia m : lista) {
            modelo.addRow(new Object[]{
                m.getIdmateria(),
                m.getNombre(),
                m.getAnio()
            });
        }
    }
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbinscribir = new javax.swing.JButton();
        jbanular = new javax.swing.JButton();
        radioinscriptas = new javax.swing.JRadioButton();
        radionoinscriptas = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtesq = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jcalu = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbinscribir.setText("Inscribir");
        jbinscribir.setEnabled(false);
        jbinscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbinscribirActionPerformed(evt);
            }
        });

        jbanular.setText("Anular Inscripcion");
        jbanular.setEnabled(false);

        radioinscriptas.setText("Materias Inscriptas");
        radioinscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioinscriptasActionPerformed(evt);
            }
        });

        radionoinscriptas.setText("Materias no inscriptas");

        jtesq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "nombre Materia", "año"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtesq);

        jLabel1.setText("Selecione el Alumno:");

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioinscriptas)
                                .addGap(52, 52, 52)
                                .addComponent(radionoinscriptas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29)
                                .addComponent(jcalu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbanular, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jbinscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jcalu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioinscriptas)
                    .addComponent(radionoinscriptas))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbanular, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbinscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbinscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbinscribirActionPerformed
       int filaseleccionada= jMateria
    }//GEN-LAST:event_jbinscribirActionPerformed

    private void radioinscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioinscriptasActionPerformed

        borrarFilaTabla();
        radionoinscriptas.setSelected(false);
        cargarDatosInscriptas();
        jbinscribir.setEnabled(false);
        jbanular.setEnabled(true);
        
    }//GEN-LAST:event_radioinscriptasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInscripcion().setVisible(true);
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbanular;
    private javax.swing.JButton jbinscribir;
    private javax.swing.JComboBox<Alumno> jcalu;
    private javax.swing.JTable jtesq;
    private javax.swing.JRadioButton radioinscriptas;
    private javax.swing.JRadioButton radionoinscriptas;
    // End of variables declaration//GEN-END:variables
}
